baseurl: https://butu.ma
languageCode: en-us
theme: stack
paginate: 7
title: 马捕头

# Change it to your Disqus shortname before using
disqusShortname: mabutou

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: favicon.ico

    footer:
        since: 2017
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 
        subtitle: 我未曾珍惜的，我不再拥有。
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus
        utterances:
            repo:
            issueTerm: pathname
            label:
            theme: preferred-color-scheme

    widgets:
        enabled:
            - archives

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: butouma

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: /about-me
          weight: -50
          pre: user

        - identifier: archives
          name: Archives
          url: /archives
          weight: -60
          pre: archives

        - identifier: photos
          name: Photos
          url: https://photos.butou.ma
          weight: -90
          pre: copyright

        - identifier: timeline
          name: Timeline
          url: https://timeline.butou.ma/
          weight: -80
          pre: clock

        - identifier: wiki
          name: Wiki
          url: https://wiki.butou.ma/
          weight: -70
          pre: link

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false