---
baseurl: https://butu.ma
languageCode: en-us
theme: stack
paginate: 7
title: 马捕头
disqusShortname: mabutou
DefaultContentLanguage: en
permalinks:
  post: "/p/:slug/"
  page: "/:slug/"
params:
  mainSections:
  - post
  featuredImageField: image
  rssFullContent: true
  favicon: favicon.ico
  footer:
    since: 2017
    customText: 
  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST
  sidebar:
    emoji: 
    subtitle: 我未曾珍惜的，我不再拥有。
    avatar:
      local: true
      src: img/avatar.png
  article:
    math: false
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0
  comments:
    enabled: true
    provider: disqus
    utterances:
      repo: 
      issueTerm: pathname
      label: 
      theme: preferred-color-scheme
  widgets:
    enabled:
    - archives
    archives:
      limit: 5
    tagCloud:
      limit: 10
  opengraph:
    twitter:
      site: butouma
      card: summary_large_image
  defaultImage:
    opengraph:
      enabled: false
      local: false
      src: 
  colorScheme:
    toggle: true
    default: auto
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
menu:
  main:
  - pre: link
    url: https://wiki.butou.ma
    name: Wiki
    weight: 4
    identifier: wiki
  - pre: clock
    url: https://t.me/s/butouma
    name: Timeline
    weight: 3
    identifier: timeline
  - pre: copyright
    url: https://photos.butou.ma
    name: Photos
    weight: 2
    identifier: photos
  - pre: home
    url: "/"
    name: Home
    weight: 1
    identifier: home
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
  - name: tags
    weight: 100
  - name: categories
    weight: 200
markup:
  highlight:
    noClasses: false
